### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by benmccann** [Nasdaq/data-link-python#37]
The first datasets I'm looking at haven't been updated in 9 months: https://data.nasdaq.com/data/FRED/DGS10-10year-treasury-constant-maturity-rate

There's no way for me to ask about it because all the help links 404 on https://help.data.nasdaq.com/category/339-data-quality-issues which is the page that came up on Google

This library hasn't been updated in 6 mos and looking at the code here makes it quite unclear who should be contacted as it seems the contact info was possibly supposed to be updated months ago and it never happened for some reason: https://github.com/Nasdaq/data-link-python/pull/29

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


Thank you for contacting the Client Success Team at Nasdaq Data Link.
Your email is very important to us and we will respond to you within 1
to 2 business days.

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you very much for reaching out.

Please be advised that the free data on Nasdaq Data Link comes from
various sources and there can be many reasons why free data may not be
updated. On that note, please also note that we don't guarantee
regular updates of free databases.

Nevertheless, your email has been forwarded to our data team. Please
kindly note that since _FRED_ is a free data feed, there is no
guaranteed timeline if/when our team will be able to investigate any
issues or apply any fixes.

Thank you for your kind understanding. 

Our helpdocs have moved, please access them here
https://help.data.nasdaq.com/ [1].

Thanks,


Links:
------
[1] https://help.data.nasdaq.com/

VAIBHAV TEMBEY
 Client Success 
 Nasdaq Data Link

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]


Links:
------
[1]
https://secure.helpscout.net/satisfaction/603967562/record/6467906197/1/
[2]
https://secure.helpscout.net/satisfaction/603967562/record/6467906197/2/
[3]
https://secure.helpscout.net/satisfaction/603967562/record/6467906197/3/

**Comment by benmccann** [comment]
[3] reply was not good. Old docs should be removed and not just left up to confuse users. Entire point of Quandl was to be a one stop shop. Thanks for killing a previously great product
